# This is a basic workflow to help you get started with Actions

name: Upload

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          name: test
          github_token: ${{secrets.GITHUB_TOKEN}}
          repo: garyzhuosim/upload-ari
          run_id: 3946133165
          path: ./down-test
          
      - name: Upload artifact
        run: ls
        working-directory: ./down-test
